import 'package:get/get.dart';
import '../controllers/orderController.dart';

class HomeController extends GetxController {
  final OrderController orderController = Get.put(OrderController());

  var selectedCategoryIndex = 0.obs;

  final List<String> categories = ['All', 'Vegetarian', 'Non-Vegetarian','Special Thali'];

  final Map<String, List<Map<String, dynamic>>> thaliItems = {
    'All': [
      {
        'id': 'veg_001',
        'name': 'Simple Veg Thali',
        'price': 120,
        'image': 'assets/images/veg (1).jpg',
        'description':
            'Basic vegetarian thali with dal, rice, roti, and seasonal sabzi',
        'rating': 4.2,
        'isVegetarian': true,
        'includes': [
          'Dal (Toor/Masoor)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Seasonal Sabzi',
          'Pickle',
        ],
        'calories': 550,
        'preparationTime': '15 mins',
      },
      {
        'id': 'veg_002',
        'name': 'Paneer Thali',
        'price': 180,
        'image': 'assets/images/veg (2).jpg',
        'description':
            'Delicious paneer curry with rice, roti, and traditional sides',
        'rating': 4.6,
        'isVegetarian': true,
        'includes': [
          'Paneer Makhani Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 680,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_003',
        'name': 'Chole Bhature Thali',
        'price': 150,
        'image': 'assets/images/veg (3).jpg',
        'description': 'Traditional chole with fried bhature bread and pickle',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Spiced Chole',
          'Bhature (1)',
          'Onion',
          'Pickle',
          'Green Chutney',
        ],
        'calories': 720,
        'preparationTime': '25 mins',
      },
      {
        'id': 'veg_004',
        'name': 'Aloo Gobi Thali',
        'price': 140,
        'image': 'assets/images/veg (4).jpg',
        'description': 'Spiced aloo and cauliflower with rice and bread',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Aloo Gobi',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
          'Salad',
        ],
        'calories': 620,
        'preparationTime': '18 mins',
      },
      {
        'id': 'veg_005',
        'name': 'Rajma Rice Thali',
        'price': 160,
        'image': 'assets/images/veg (5).jpg',
        'description': 'Kidney beans curry with steamed rice and side dishes',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Rajma Curry',
          'Steamed Rice',
          'Wheat Roti (1)',
          'Onion & Lemon',
          'Pickle',
        ],
        'calories': 590,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_006',
        'name': 'Dal Makhani Thali',
        'price': 170,
        'image': 'assets/images/veg (6).jpg',
        'description':
            'Creamy dal makhani with butter, served with rice and roti',
        'rating': 4.5,
        'isVegetarian': true,
        'includes': [
          'Dal Makhani',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 650,
        'preparationTime': '22 mins',
      },
      {
        'id': 'veg_007',
        'name': 'Baingan Bharta Thali',
        'price': 145,
        'image': 'assets/images/veg (7).jpg',
        'description': 'Roasted eggplant curry with traditional Indian spices',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Baingan Bharta',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
          'Onion',
        ],
        'calories': 580,
        'preparationTime': '18 mins',
      },
      {
        'id': 'veg_008',
        'name': 'Chana Masala Thali',
        'price': 155,
        'image': 'assets/images/veg (8).jpg',
        'description':
            'Spiced chickpea curry served with rice and Indian breads',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Chana Masala',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Onion',
          'Pickle',
          'Salad',
        ],
        'calories': 610,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_009',
        'name': 'Methi Aloo Thali',
        'price': 135,
        'image': 'assets/images/veg (9).jpg',
        'description': 'Fenugreek leaves with potatoes in aromatic spices',
        'rating': 4.2,
        'isVegetarian': true,
        'includes': [
          'Methi Aloo',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
        ],
        'calories': 560,
        'preparationTime': '17 mins',
      },
      {
        'id': 'veg_010',
        'name': 'Palak Paneer Thali',
        'price': 190,
        'image': 'assets/images/veg (10).jpg',
        'description':
            'Spinach and paneer in rich cream sauce with bread and rice',
        'rating': 4.7,
        'isVegetarian': true,
        'includes': [
          'Palak Paneer',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 700,
        'preparationTime': '22 mins',
      },
      {
        'id': 'veg_011',
        'name': 'Mixed Vegetable Thali',
        'price': 140,
        'image': 'assets/images/veg (11).jpg',
        'description': 'Assorted vegetables in mild curry with rice and bread',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Mixed Vegetable Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
          'Salad',
        ],
        'calories': 600,
        'preparationTime': '19 mins',
      },
      {
        'id': 'veg_012',
        'name': 'Loki Chana Thali',
        'price': 135,
        'image': 'assets/images/veg (1).jpg',
        'description': 'Bottle gourd with chickpeas in authentic spices',
        'rating': 4.2,
        'isVegetarian': true,
        'includes': [


          'Loki Chana Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Pickle',
          'Onion',
        ],
        'calories': 570,
        'preparationTime': '18 mins',
      },
      {
        'id': 'veg_013',
        'name': 'Shahi Paneer Thali',
        'price': 210,
        'image': 'assets/images/veg (13).jpg',
        'description': 'Premium paneer in rich tomato-based creamy sauce',
        'rating': 4.8,
        'isVegetarian': true,
        'includes': [
          'Shahi Paneer',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 720,
        'preparationTime': '24 mins',
      },
      {
        'id': 'veg_014',
        'name': 'Arhar Dal Thali',
        'price': 130,
        'image': 'assets/images/veg (14).jpg',
        'description':
            'Traditional arhar dal with tempering, served with rice and roti',
        'rating': 4.1,
        'isVegetarian': true,
        'includes': [
          'Arhar Dal',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Sabzi',
          'Pickle',
        ],
        'calories': 540,
        'preparationTime': '16 mins',
      },
      {
        'id': 'veg_015',
        'name': 'Moong Dal Makhani Thali',
        'price': 165,
        'image': 'assets/images/veg (15).jpg',
        'description': 'Creamy moong dal with butter and cream',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Moong Dal Makhani',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 630,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_016',
        'name': 'Broccoli Garlic Thali',
        'price': 155,
        'image': 'assets/images/veg (16).jpg',
        'description':
            'Steamed broccoli with garlic tempering and Indian spices',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Broccoli Garlic',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Salad',
          'Pickle',
        ],
        'calories': 520,
        'preparationTime': '17 mins',
      },
      {
        'id': 'veg_017',
        'name': 'Mushroom Masala Thali',
        'price': 170,
        'image': 'assets/images/veg (17).jpg',
        'description': 'Sautéed mushrooms in spiced tomato gravy',
        'rating': 4.5,
        'isVegetarian': true,
        'includes': [
          'Mushroom Masala',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 640,
        'preparationTime': '21 mins',
      },
      {
        'id': 'veg_018',
        'name': 'Bitter Gourd Thali',
        'price': 140,
        'image': 'assets/images/veg (18).jpg',
        'description': 'Crispy fried bitter gourd with onions and spices',
        'rating': 4.2,
        'isVegetarian': true,
        'includes': [
          'Crispy Bitter Gourd',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
        ],
        'calories': 550,
        'preparationTime': '18 mins',
      },
      {
        'id': 'veg_020',
        'name': 'Corn Capsicum Thali',
        'price': 160,
        'image': 'assets/images/veg (20).jpg',
        'description': 'Sweet corn with bell peppers in creamy sauce',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Corn Capsicum Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 600,
        'preparationTime': '19 mins',
      },

      // Non-Vegetarian Thalis
      {
        'id': 'nonveg_001',
        'name': 'Butter Chicken Thali',
        'price': 240,
        'image': 'assets/images/nonVeg (1).jpg',
        'description':
            'Tender chicken in rich tomato-based cream sauce with rice and roti',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': [
          'Butter Chicken',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 750,
        'preparationTime': '25 mins',
      },
      {
        'id': 'nonveg_002',
        'name': 'Chicken Tikka Masala Thali',
        'price': 250,
        'image': 'assets/images/nonVeg (2).jpg',
        'description': 'Marinated and grilled chicken in aromatic tomato gravy',
        'rating': 4.8,
        'isVegetarian': false,
        'includes': [
          'Chicken Tikka Masala',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 780,
        'preparationTime': '28 mins',
      },
      {
        'id': 'nonveg_003',
        'name': 'Chicken Biryani Thali',
        'price': 260,
        'image': 'assets/images/nonVeg (3).jpg',
        'description':
            'Fragrant basmati rice cooked with tender chicken pieces',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': ['Chicken Biryani', 'Raita', 'Pickle', 'Salad', 'Shorba'],
        'calories': 820,
        'preparationTime': '30 mins',
      },
      {
        'id': 'nonveg_004',
        'name': 'Tandoori Chicken Thali',
        'price': 230,
        'image': 'assets/images/nonVeg (4).jpg',
        'description':
            'Smoky tandoori chicken with rice, roti, and traditional sides',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Tandoori Chicken (½)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Lemon',
          'Salad',
          'Onion',
        ],
        'calories': 700,
        'preparationTime': '24 mins',
      },
      {
        'id': 'nonveg_005',
        'name': 'Chicken Chettinad Thali',
        'price': 245,
        'image': 'assets/images/nonVeg (5).jpg',
        'description':
            'Spicy South Indian chicken curry with coconut and spices',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Chicken Chettinad',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Pickle',
          'Salad',
        ],
        'calories': 760,
        'preparationTime': '26 mins',
      },
      {
        'id': 'nonveg_006',
        'name': 'Mutton Rogan Josh Thali',
        'price': 280,
        'image': 'assets/images/nonVeg (6).jpg',
        'description':
            'Tender mutton pieces in aromatic tomato and yogurt gravy',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': [
          'Mutton Rogan Josh',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 820,
        'preparationTime': '32 mins',
      },
      {
        'id': 'nonveg_007',
        'name': 'Chicken Korma Thali',
        'price': 255,
        'image': 'assets/images/nonVeg (7).jpg',
        'description': 'Creamy chicken curry with nuts and aromatic spices',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Chicken Korma',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 800,
        'preparationTime': '27 mins',
      },
      {
        'id': 'nonveg_008',
        'name': 'Prawn Curry Thali',
        'price': 290,
        'image': 'assets/images/nonVeg (8).jpg',
        'description':
            'Fresh prawns in coconut-based curry with rice and bread',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': [
          'Prawn Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
        ],
        'calories': 740,
        'preparationTime': '25 mins',
      },
      {
        'id': 'nonveg_009',
        'name': 'Fish Curry Thali',
        'price': 270,
        'image': 'assets/images/nonVeg (9).jpg',
        'description': 'Fresh fish in aromatic spiced gravy with rice and roti',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Fish Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
        ],
        'calories': 680,
        'preparationTime': '23 mins',
      },
      {
        'id': 'nonveg_010',
        'name': 'Chicken Do Pyaza Thali',
        'price': 235,
        'image': 'assets/images/nonVeg (10).jpg',
        'description': 'Chicken with lots of onions cooked in aromatic spices',
        'rating': 4.5,
        'isVegetarian': false,
        'includes': [
          'Chicken Do Pyaza',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Onion',
          'Pickle',
          'Salad',
        ],
        'calories': 720,
        'preparationTime': '24 mins',
      },
      {
        'id': 'nonveg_011',
        'name': 'Mutton Biryani Thali',
        'price': 285,
        'image': 'assets/images/nonVeg (11).jpg',
        'description':
            'Fragrant basmati rice with tender mutton cooked with spices',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': ['Mutton Biryani', 'Raita', 'Pickle', 'Salad', 'Shorba'],
        'calories': 850,
        'preparationTime': '35 mins',
      },
      {
        'id': 'nonveg_012',
        'name': 'Chicken Vindaloo Thali',
        'price': 240,
        'image': 'assets/images/nonVeg (12).jpg',
        'description':
            'Spicy chicken curry with potatoes and vinegar-based gravy',
        'rating': 4.5,
        'isVegetarian': false,
        'includes': [
          'Chicken Vindaloo',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Pickle',
          'Salad',
        ],
        'calories': 740,
        'preparationTime': '25 mins',
      },
      {
        'id': 'nonveg_013',
        'name': 'Keema Pav Thali',
        'price': 220,
        'image': 'assets/images/nonVeg (13).jpg',
        'description': 'Ground chicken cooked with peas and served with pav',
        'rating': 4.4,
        'isVegetarian': false,
        'includes': ['Keema', 'Pav (2)', 'Onion', 'Coriander', 'Pickle'],
        'calories': 700,
        'preparationTime': '20 mins',
      },
      {
        'id': 'nonveg_014',
        'name': 'Egg Curry Thali',
        'price': 180,
        'image': 'assets/images/nonVeg (14).jpg',
        'description': 'Soft-boiled eggs in spiced tomato-based curry',
        'rating': 4.3,
        'isVegetarian': false,
        'includes': [
          'Egg Curry (2 eggs)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Pickle',
          'Salad',
        ],
        'calories': 620,
        'preparationTime': '18 mins',
      },
      {
        'id': 'nonveg_015',
        'name': 'Lamb Chops Thali',
        'price': 310,
        'image': 'assets/images/nonVeg (15).jpg',
        'description':
            'Tender lamb chops marinated and grilled with rice and roti',
        'rating': 4.8,
        'isVegetarian': false,
        'includes': [
          'Lamb Chops (4)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Mint Chutney',
          'Salad',
          'Lemon',
        ],
        'calories': 880,
        'preparationTime': '30 mins',
      },
      {
        'id': 'nonveg_016',
        'name': 'Dhaba Style Chicken Thali',
        'price': 225,
        'image': 'assets/images/nonVeg (16).jpg',
        'description':
            'Traditional roadside dhaba-style chicken with rustic flavors',
        'rating': 4.4,
        'isVegetarian': false,
        'includes': [
          'Dhaba Chicken',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Onion',
          'Pickle',
          'Curd',
        ],
        'calories': 710,
        'preparationTime': '22 mins',
      },
    ],

    'Vegetarian': [
      {
        'id': 'veg_001',
        'name': 'Simple Veg Thali',
        'price': 120,
        'image': 'assets/images/veg (1).jpg',
        'description':
            'Basic vegetarian thali with dal, rice, roti, and seasonal sabzi',
        'rating': 4.2,
        'isVegetarian': true,
        'includes': [
          'Dal (Toor/Masoor)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Seasonal Sabzi',
          'Pickle',
        ],
        'calories': 550,
        'preparationTime': '15 mins',
      },
      {
        'id': 'veg_002',
        'name': 'Paneer Thali',
        'price': 180,
        'image': 'assets/images/veg (2).jpg',
        'description':
            'Delicious paneer curry with rice, roti, and traditional sides',
        'rating': 4.6,
        'isVegetarian': true,
        'includes': [
          'Paneer Makhani Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 680,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_003',
        'name': 'Chole Bhature Thali',
        'price': 150,
        'image': 'assets/images/veg (3).jpg',
        'description': 'Traditional chole with fried bhature bread and pickle',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Spiced Chole',
          'Bhature (1)',
          'Onion',
          'Pickle',
          'Green Chutney',
        ],
        'calories': 720,
        'preparationTime': '25 mins',
      },
      {
        'id': 'veg_004',
        'name': 'Aloo Gobi Thali',
        'price': 140,
        'image': 'assets/images/veg (4).jpg',
        'description': 'Spiced aloo and cauliflower with rice and bread',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Aloo Gobi',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
          'Salad',
        ],
        'calories': 620,
        'preparationTime': '18 mins',
      },
      {
        'id': 'veg_005',
        'name': 'Rajma Rice Thali',
        'price': 160,
        'image': 'assets/images/veg (5).jpg',
        'description': 'Kidney beans curry with steamed rice and side dishes',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Rajma Curry',
          'Steamed Rice',
          'Wheat Roti (1)',
          'Onion & Lemon',
          'Pickle',
        ],
        'calories': 590,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_006',
        'name': 'Dal Makhani Thali',
        'price': 170,
        'image': 'assets/images/veg (6).jpg',
        'description':
            'Creamy dal makhani with butter, served with rice and roti',
        'rating': 4.5,
        'isVegetarian': true,
        'includes': [
          'Dal Makhani',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 650,
        'preparationTime': '22 mins',
      },
      {
        'id': 'veg_007',
        'name': 'Baingan Bharta Thali',
        'price': 145,
        'image': 'assets/images/veg (7).jpg',
        'description': 'Roasted eggplant curry with traditional Indian spices',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Baingan Bharta',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
          'Onion',
        ],
        'calories': 580,
        'preparationTime': '18 mins',
      },
      {
        'id': 'veg_008',
        'name': 'Chana Masala Thali',
        'price': 155,
        'image': 'assets/images/veg (8).jpg',
        'description':
            'Spiced chickpea curry served with rice and Indian breads',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Chana Masala',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Onion',
          'Pickle',
          'Salad',
        ],
        'calories': 610,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_009',
        'name': 'Methi Aloo Thali',
        'price': 135,
        'image': 'assets/images/veg (9).jpg',
        'description': 'Fenugreek leaves with potatoes in aromatic spices',
        'rating': 4.2,
        'isVegetarian': true,
        'includes': [
          'Methi Aloo',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
        ],
        'calories': 560,
        'preparationTime': '17 mins',
      },
      {
        'id': 'veg_010',
        'name': 'Palak Paneer Thali',
        'price': 190,
        'image': 'assets/images/veg (10).jpg',
        'description':
            'Spinach and paneer in rich cream sauce with bread and rice',
        'rating': 4.7,
        'isVegetarian': true,
        'includes': [
          'Palak Paneer',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 700,
        'preparationTime': '22 mins',
      },
      {
        'id': 'veg_011',
        'name': 'Mixed Vegetable Thali',
        'price': 140,
        'image': 'assets/images/veg (11).jpg',
        'description': 'Assorted vegetables in mild curry with rice and bread',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Mixed Vegetable Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
          'Salad',
        ],
        'calories': 600,
        'preparationTime': '19 mins',
      },
      {
        'id': 'veg_013',
        'name': 'Shahi Paneer Thali',
        'price': 210,
        'image': 'assets/images/veg (13).jpg',
        'description': 'Premium paneer in rich tomato-based creamy sauce',
        'rating': 4.8,
        'isVegetarian': true,
        'includes': [
          'Shahi Paneer',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 720,
        'preparationTime': '24 mins',
      },
      {
        'id': 'veg_014',
        'name': 'Arhar Dal Thali',
        'price': 130,
        'image': 'assets/images/veg (14).jpg',
        'description':
            'Traditional arhar dal with tempering, served with rice and roti',
        'rating': 4.1,
        'isVegetarian': true,
        'includes': [
          'Arhar Dal',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Sabzi',
          'Pickle',
        ],
        'calories': 540,
        'preparationTime': '16 mins',
      },
      {
        'id': 'veg_015',
        'name': 'Moong Dal Makhani Thali',
        'price': 165,
        'image': 'assets/images/veg (15).jpg',
        'description': 'Creamy moong dal with butter and cream',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Moong Dal Makhani',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 630,
        'preparationTime': '20 mins',
      },
      {
        'id': 'veg_016',
        'name': 'Broccoli Garlic Thali',
        'price': 155,
        'image': 'assets/images/veg (16).jpg',
        'description':
            'Steamed broccoli with garlic tempering and Indian spices',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Broccoli Garlic',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Salad',
          'Pickle',
        ],
        'calories': 520,
        'preparationTime': '17 mins',
      },
      {
        'id': 'veg_017',
        'name': 'Mushroom Masala Thali',
        'price': 170,
        'image': 'assets/images/veg (17).jpg',
        'description': 'Sautéed mushrooms in spiced tomato gravy',
        'rating': 4.5,
        'isVegetarian': true,
        'includes': [
          'Mushroom Masala',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 640,
        'preparationTime': '21 mins',
      },
      {
        'id': 'veg_018',
        'name': 'Bitter Gourd Thali',
        'price': 140,
        'image': 'assets/images/veg (18).jpg',
        'description': 'Crispy fried bitter gourd with onions and spices',
        'rating': 4.2,
        'isVegetarian': true,
        'includes': [
          'Crispy Bitter Gourd',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Dal',
          'Pickle',
        ],
        'calories': 550,
        'preparationTime': '18 mins',
      },
      {
        'id': 'veg_020',
        'name': 'Corn Capsicum Thali',
        'price': 160,
        'image': 'assets/images/veg (20).jpg',
        'description': 'Sweet corn with bell peppers in creamy sauce',
        'rating': 4.4,
        'isVegetarian': true,
        'includes': [
          'Corn Capsicum Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 600,
        'preparationTime': '19 mins',
      },
    ],

    'Non-Vegetarian': [
      {
        'id': 'nonveg_001',
        'name': 'Butter Chicken Thali',
        'price': 240,
        'image': 'assets/images/nonVeg (1).jpg',
        'description':
            'Tender chicken in rich tomato-based cream sauce with rice and roti',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': [
          'Butter Chicken',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 750,
        'preparationTime': '25 mins',
      },
      {
        'id': 'nonveg_002',
        'name': 'Chicken Tikka Masala Thali',
        'price': 250,
        'image': 'assets/images/nonVeg (2).jpg',
        'description': 'Marinated and grilled chicken in aromatic tomato gravy',
        'rating': 4.8,
        'isVegetarian': false,
        'includes': [
          'Chicken Tikka Masala',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 780,
        'preparationTime': '28 mins',
      },
      {
        'id': 'nonveg_003',
        'name': 'Chicken Biryani Thali',
        'price': 260,
        'image': 'assets/images/nonVeg (3).jpg',
        'description':
            'Fragrant basmati rice cooked with tender chicken pieces',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': ['Chicken Biryani', 'Raita', 'Pickle', 'Salad', 'Shorba'],
        'calories': 820,
        'preparationTime': '30 mins',
      },
      {
        'id': 'nonveg_004',
        'name': 'Tandoori Chicken Thali',
        'price': 230,
        'image': 'assets/images/nonVeg (4).jpg',
        'description':
            'Smoky tandoori chicken with rice, roti, and traditional sides',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Tandoori Chicken (½)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Lemon',
          'Salad',
          'Onion',
        ],
        'calories': 700,
        'preparationTime': '24 mins',
      },
      {
        'id': 'nonveg_005',
        'name': 'Chicken Chettinad Thali',
        'price': 245,
        'image': 'assets/images/nonVeg (5).jpg',
        'description':
            'Spicy South Indian chicken curry with coconut and spices',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Chicken Chettinad',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Pickle',
          'Salad',
        ],
        'calories': 760,
        'preparationTime': '26 mins',
      },
      {
        'id': 'nonveg_006',
        'name': 'Mutton Rogan Josh Thali',
        'price': 280,
        'image': 'assets/images/nonVeg (6).jpg',
        'description':
            'Tender mutton pieces in aromatic tomato and yogurt gravy',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': [
          'Mutton Rogan Josh',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 820,
        'preparationTime': '32 mins',
      },
      {
        'id': 'nonveg_007',
        'name': 'Chicken Korma Thali',
        'price': 255,
        'image': 'assets/images/nonVeg (7).jpg',
        'description': 'Creamy chicken curry with nuts and aromatic spices',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Chicken Korma',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
          'Curd',
        ],
        'calories': 800,
        'preparationTime': '27 mins',
      },
      {
        'id': 'nonveg_008',
        'name': 'Prawn Curry Thali',
        'price': 290,
        'image': 'assets/images/nonVeg (8).jpg',
        'description':
            'Fresh prawns in coconut-based curry with rice and bread',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': [
          'Prawn Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
        ],
        'calories': 740,
        'preparationTime': '25 mins',
      },
      {
        'id': 'nonveg_009',
        'name': 'Fish Curry Thali',
        'price': 270,
        'image': 'assets/images/nonVeg (9).jpg',
        'description': 'Fresh fish in aromatic spiced gravy with rice and roti',
        'rating': 4.6,
        'isVegetarian': false,
        'includes': [
          'Fish Curry',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Salad',
          'Pickle',
        ],
        'calories': 680,
        'preparationTime': '23 mins',
      },
      {
        'id': 'nonveg_010',
        'name': 'Chicken Do Pyaza Thali',
        'price': 235,
        'image': 'assets/images/nonVeg (10).jpg',
        'description': 'Chicken with lots of onions cooked in aromatic spices',
        'rating': 4.5,
        'isVegetarian': false,
        'includes': [
          'Chicken Do Pyaza',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Onion',
          'Pickle',
          'Salad',
        ],
        'calories': 720,
        'preparationTime': '24 mins',
      },
      {
        'id': 'nonveg_011',
        'name': 'Mutton Biryani Thali',
        'price': 285,
        'image': 'assets/images/nonVeg (11).jpg',
        'description':
            'Fragrant basmati rice with tender mutton cooked with spices',
        'rating': 4.7,
        'isVegetarian': false,
        'includes': ['Mutton Biryani', 'Raita', 'Pickle', 'Salad', 'Shorba'],
        'calories': 850,
        'preparationTime': '35 mins',
      },
      {
        'id': 'nonveg_012',
        'name': 'Chicken Vindaloo Thali',
        'price': 240,
        'image': 'assets/images/nonVeg (12).jpg',
        'description':
            'Spicy chicken curry with potatoes and vinegar-based gravy',
        'rating': 4.5,
        'isVegetarian': false,
        'includes': [
          'Chicken Vindaloo',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Pickle',
          'Salad',
        ],
        'calories': 740,
        'preparationTime': '25 mins',
      },
      {
        'id': 'nonveg_013',
        'name': 'Keema Pav Thali',
        'price': 220,
        'image': 'assets/images/nonVeg (13).jpg',
        'description': 'Ground chicken cooked with peas and served with pav',
        'rating': 4.4,
        'isVegetarian': false,
        'includes': ['Keema', 'Pav (2)', 'Onion', 'Coriander', 'Pickle'],
        'calories': 700,
        'preparationTime': '20 mins',
      },
      {
        'id': 'nonveg_014',
        'name': 'Egg Curry Thali',
        'price': 180,
        'image': 'assets/images/nonVeg (14).jpg',
        'description': 'Soft-boiled eggs in spiced tomato-based curry',
        'rating': 4.3,
        'isVegetarian': false,
        'includes': [
          'Egg Curry (2 eggs)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Pickle',
          'Salad',
        ],
        'calories': 620,
        'preparationTime': '18 mins',
      },
      {
        'id': 'nonveg_015',
        'name': 'Lamb Chops Thali',
        'price': 310,
        'image': 'assets/images/nonVeg (15).jpg',
        'description':
            'Tender lamb chops marinated and grilled with rice and roti',
        'rating': 4.8,
        'isVegetarian': false,
        'includes': [
          'Lamb Chops (4)',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Mint Chutney',
          'Salad',
          'Lemon',
        ],
        'calories': 880,
        'preparationTime': '30 mins',
      },
      {
        'id': 'nonveg_016',
        'name': 'Dhaba Style Chicken Thali',
        'price': 225,
        'image': 'assets/images/nonVeg (16).jpg',
        'description':
            'Traditional roadside dhaba-style chicken with rustic flavors',
        'rating': 4.4,
        'isVegetarian': false,
        'includes': [
          'Dhaba Chicken',
          'Basmati Rice',
          'Wheat Roti (2)',
          'Onion',
          'Pickle',
          'Curd',
        ],
        'calories': 710,
        'preparationTime': '22 mins',
      },
    ],
    'Special Thali': [{
      'id': 'veg_012',
      'name': 'Indian Special Thali',
      'price': 135,
      'image': 'assets/images/veg (12).jpg',
      'description': 'Bottle gourd with chickpeas in authentic spices',
      'rating': 4.2,
      'isVegetarian': true,
      'includes': [
        'Loki Chana Curry',
        'Basmati Rice',
        'Wheat Roti (2)',
        'Pickle',
        'Onion',
      ],
      'calories': 570,
      'preparationTime': '18 mins',
    },
      {
        'id': 'veg_019',
        'name': 'Sprouts Salad Thali',
        'price': 145,
        'image': 'assets/images/veg (19).jpg',
        'description':
        'Healthy sprouts salad with light curry and whole wheat bread',
        'rating': 4.3,
        'isVegetarian': true,
        'includes': [
          'Sprouts Salad',
          'Light Curry',
          'Whole Wheat Roti (2)',
          'Rice',
          'Pickle',
        ],
        'calories': 480,
        'preparationTime': '15 mins',
      },]
  };
}
